pref("extensions.doubanradio.lovestring",'正在{radio}听{artist}《{album}》专辑的《{title}》。{mp3url}');
pref("extensions.doubanradio.shareservice", 'sina');
pref("extensions.doubanradio.filter", true);
pref("extensions.doubanradio.debug", false);
pref("extensions.doubanradio.share", true);
pref("extensions.doubanradio.autoshowinfo", true);
pref("extensions.doubanradio.mp3path", "");
pref("extensions.doubanradio.synclyric", true);
pref("extensions.doubanradio.thirdpartytool", false);
pref("extensions.doubanradio.downloadremind", true);
pref("extensions.doubanradio.writetag", true);
pref("extensions.doubanradio.color", 'orange');
pref("extensions.doubanradio.osdpattern","<message><span color='{color}'>{lyric}</span></message>");
pref("extensions.doubanradio.versionrec", "0.1");
pref("extensions.doubanradio.versionrec2", "1beta1");
pref("extensions.doubanradio.currentcid", "1");
pref("extensions.doubanradio.currentrid", "0");
pref("extensions.doubanradio.autoupdatechannel",true);
pref("extensions.doubanradio.id3v1",true);
pref("extensions.doubanradio.id3v1.encoding", "gb2312");
pref("extensions.doubanradio.id3v2",false);
pref("extensions.doubanradio.followflg",true);
pref("extensions.doubanradio.locallyric",true);
pref("extensions.doubanradio.showinurlbar",true);
pref("extensions.doubanradio.addressbar",true);
pref("extensions.doubanradio.artistfliter",true);
pref("extensions.doubanradio.artistfilterlist","");
pref("extensions.doubanradio.publicinfo",true);
pref("extensions.doubanradio.albumlist", "{}");
pref("extensions.doubanradio.artistlist", "{}");
pref("extensions.doubanradio.recentchannel", "[]");
pref("extensions.doubanradio.lyricengine", "yahoo");
pref("extensions.doubanradio.queuedeep", 6);
pref('extensions.doubanradio.channel_sina','{"C81":"新歌","C82":"圣诞节","C95":"蔡琴","C97":"梅艳芳","C89":"richard","C99":"黄舒骏","C100":"齐秦","C90":"莫扎特","C53":"原声","C67":"怀旧","C58":"爵士","C85":"林夕","C98":"英文","C73":"射手","C86":"列侬","C51":"情歌","C84":"三角龙","C48":"电音","C56":"独立音乐","C57":"旅行","C54":"女生","C64":"世界杯","C69":"R&B","C83":"光棍节","C59":"摇滚","C62":"公路","C60":"法语","C52":"晚安","C68":"古典","C65":"嘻哈","C49":"拉丁","C76":"水瓶","C75":"双鱼","C74":"白羊","C79":"金牛","C77":"双子","C71":"巨蟹","C80":"狮子","C70":"处女","C72":"天枰","C66":"天蝎","C78":"魔蝎"}');
pref('extensions.doubanradio.channel_renren','{"C267":"华语先锋","C266":"华语怀旧","C265":"聆听寂寞","C259":"欧美流行","C288":"欧美怀旧","C260":"摇滚态度","C261":"重型音乐","C263":"东瀛来风","C264":"纯音乐"}');
pref("extensions.doubanradio.channel_douban", '{"C0":"私人频道","C1":"华语","C6":"粤语","C2":"欧美","C27":"古典","C26":"豆瓣音乐人","C22":"法语","C17":"日语","C18":"韩语","C13":"爵士","C14":"电子","C16":"R&B","C15":"说唱","C7":"摇滚","C8":"民谣","C10":"电影原声","C9":"轻音乐","C20":"女声","C3":"七零","C4":"八零","C5":"九零","C28":"动漫","C31":"NB敢动","C30":"BMW+CLUB3+"}');
pref("extensions.doubanradio.thirdpartytoolpath", "/usr/bin/gnome-osd-client");
// https://developer.mozilla.org/en/Localizing_extension_descriptions
pref("extensions.doubanradio@mattmonkey.description", "chrome://doubanradio/locale/overlay.properties");

